import {
    playlistCoverFive,
    playlistCoverFour,
    playlistCoverOne,
    playlistCoverSeven,
    playlistCoverThree,
    playlistCoverTwo,
    playlistCoverZero,
} from '../assets/images';

export const playlists = [
    {
        name: 'Hicathon Dev',
        curator: 'HEN Radio',
        description: 'The tracks that made hen.radio, listened to on repeat for hackday development',
        img: playlistCoverZero,
        tracks: [
            {
                id: 48594,
                name: 'A l\'Ouest',
                src: 'https://ipfs.io/ipfs/QmawLCNM666CsHajN7MfJH9baWq2JRshxXX7QETL9dR4NA',
                mimeType: 'audio/ogg',
                creator: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f',
            },
            {
                id: 44540,
                name: 'BUDS',
                src: 'https://ipfs.io/ipfs/QmaRtMtfQEbUEj39gwCSNzcLPhBaTEnTXsFjWjeXNPMe3c',
                mimeType: 'audio/mpeg',
                creator: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp',
            },
            {
                id: 16396,
                name: 'The Air That Never Was',
                src: 'https://ipfs.io/ipfs/QmXpvmA6R4nJmeZsDXJY2EyUeYcM5iCg2Ww1jtjTnrf5iQ',
                mimeType: 'audio/mpeg',
                creator: 'tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ',
            },
            {
                id: 5302,
                name: 'Dub Stars',
                src: 'https://ipfs.io/ipfs/Qmd8vTe22AdcYV84hTD2UEZFDicZZNf4j9bUBfDQsidy11',
                mimeType: 'audio/mpeg',
                creator: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f',
            },
            {
                id: 41309,
                name: 'Improvisation for Melody Owen',
                src: 'https://ipfs.io/ipfs/QmXLBb1b5c3hA3Rsccs19Zw9PCQEuJiU3drAyfFnTa2ZSP',
                mimeType: 'audio/mpeg',
                creator: 'tz1YJvMiZyXnzvV9pxtAiuCFvaG7XoBZhbUQ',
            },
            {
                id: 5298,
                name: 'Melancome',
                src: 'https://ipfs.io/ipfs/QmNNrraeevcUhDT4saUA6W1AqiukZvvyRtroCf57PhjjyV',
                mimeType: 'audio/mpeg',
                creator: 'tz2EaL8HTqjZhVAWrQ3Ddp4wNCxPeE8CtM5f',
            },
            {
                id: 44528,
                name: '|WOAH}C00L|',
                src: 'https://ipfs.io/ipfs/QmYRADeeCDWyayLm8jrePE7EzVo9NXTBgXSfpshQcMuCEm',
                mimeType: 'audio/mpeg',
                creator: 'tz1iG2tUSgBhUHnjNKnrNVrdtFhZEq9FzPEp',
            },
        ],
    },
    {
        name: 'Eclectic Coups de Coeur #1',
        curator: 'Lauzaki',
        description: 'A mixed bag of HEN gems',
        img: playlistCoverOne,
        tracks: [
            {
                id: 17575,
                name: 'Dancing Bones',
                src: 'https://ipfs.io/ipfs/QmNot4YVcRqByEiiNHKwocR1Ncnab9VGdHtUbLKD5Q14bT',
                mimeType: 'audio/mpeg',
                creator: 'tz1VQwSyQPA1owaqZ2RUkDEKsdZsfQPVvVbN',
            },
            {
                id: 11305,
                name: 'rumpy wants a baby',
                src: 'https://ipfs.io/ipfs/QmUfPW1eBdD7naLGopdpJyXYTezpU46Bkam9d2kx96JoFg',
                mimeType: 'audio/mpeg',
                creator: 'tz1ZQ3RF4Qk2P9qau3ya4hKMxqq42SEjhbYw',
            },
            {
                id: 97695,
                name: 'PEACE',
                src: 'https://ipfs.io/ipfs/QmVX35MDiPpsXW3gtKumNL2j44ZzWr5QPZP5vbgHDE5VoE',
                mimeType: 'audio/mpeg',
                creator: 'tz1Uj8B2iVVcVV7FHmFL7PTZdNK4onhXP1Bs',
            },
            {
                id: 97684,
                name: 'SUNDAYSUSET',
                src: 'https://ipfs.io/ipfs/QmdmgwMFxarbpEk1eZzUm2JEiBg9VGoLmBphyUDrSbwU4w',
                mimeType: 'audio/mpeg',
                creator: 'tz1Uj8B2iVVcVV7FHmFL7PTZdNK4onhXP1Bs',
            },
            {
                id: 101079,
                name: 'Crypto Noise series #04',
                src: 'https://ipfs.io/ipfs/QmatzMuSP2XAWDMpjUxmXeFDCSJAtePjhte7J58DE4ssKp',
                mimeType: 'audio/wav',
                creator: 'tz1cP6n3wsdGA57YRizTwk2ks6uKV2gNNGkC',
            },
            {
                id: 9482,
                name: 'gpp udah makan by bagvs',
                src: 'https://ipfs.io/ipfs/QmaJLxXppTPvLJjLFCpntAPT5TwaShxeGEqnFTP6AborBt',
                mimeType: 'audio/mpeg',
                creator: 'tz1PTddXFRZDHnzy8k34XiKwy7p2vabY8Qxo',
            },
            {
                id: 12095,
                name: 'Malachi Basden and Wes Anderson -- I Can\'t Get Started',
                src: 'https://ipfs.io/ipfs/Qmdq5oLpi5gWPk4QsJ3HcJuAusNr2bV7L1EBHddJYDByUd',
                mimeType: 'audio/mpeg',
                creator: 'tz1Z7PUrxjaev1EM2SeGtetiZgZedrYvgFmY',
            },
            {
                id: 43386,
                name: 'continuum_after_latency',
                src: 'https://ipfs.io/ipfs/Qmb92ifujVsctJL5R8X25prWjNjjuDCWScysEXiAZSrD2v',
                mimeType: 'audio/mpeg',
                creator: 'tz2MR9zog3QaSKRMsxMRqYtDevwoRKVvMQX7',
            },
        ],
    },
    {
        name: 'Ambient Atmosphere',
        curator: 'HEN Radio',
        description: 'Ambient Future Atmosphere',
        img: playlistCoverTwo,
        tracks: [
            {
                id: 8577,
                name: 'Geometrical Psychology #8',
                src: 'https://ipfs.io/ipfs/QmfHLRCnhFY5oBsmE9gKH6xjFUpbjNcqRG8XKTm52jaiHa',
                mimeType: 'audio/mpeg',
                creator: 'tz1TA2GsoJmC6G57DZfMw9cj5Z8ztviGBzU7',
            },
            {
                id: 6337,
                name: 'Eurorack ambient jam #1',
                src: 'https://ipfs.io/ipfs/QmUmhLsTPKRjwJN3eNfYAJ9Hw1SaRbC8gQTky9MBPfWcr1',
                mimeType: 'audio/mpeg',
                creator: 'tz1etmVTu5kPrSZjQPNF2nE79xyKddjwguyz',
            },
            {
                id: 10045,
                name: 'Eurorack ambient jam #4',
                src: 'https://ipfs.io/ipfs/QmVdoqKAQNQNJ8YBGTk6pXsrXNZqvErHNzxKFg7cnPn9xj',
                mimeType: 'audio/mpeg',
                creator: 'tz1etmVTu5kPrSZjQPNF2nE79xyKddjwguyz',
            },
        ],
    },
    {
        name: 'Experimental Brazil',
        curator: 'HEN Radio',
        description: 'Experimental Brazil',
        img: playlistCoverThree,
        tracks: [
            {
                id: 44945,
                name: 'Bface - Touch Ya!',
                src: 'https://ipfs.io/ipfs/Qmf9BCvmWyTwXjFiyTTswRehfSmBF2JPowYutDH1um4akG',
                mimeType: 'audio/mpeg',
                creator: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S',
            },
            {
                id: 45003,
                name: 'Bface - 70skrl',
                src: 'https://ipfs.io/ipfs/QmaWPAQjpotsgbv66aECT2SbbSXKDhjF9FxGrozVP2DYyn',
                mimeType: 'audio/mpeg',
                creator: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S',
            },
            {
                id: 44984,
                name: 'Bface - Vida Severina',
                src: 'https://ipfs.io/ipfs/QmQJ86BBKZKmoM8bJDSZ2AohKeWv1atP21CrudQhukfU8D',
                mimeType: 'audio/mpeg',
                creator: 'tz1QJF39YnffgHKHMryknBWABVtmSKmPhJ6S',
            },
        ],
    },
    {
        name: 'House',
        curator: 'HEN Radio',
        description: 'House on the soft side',
        img: playlistCoverFour,
        tracks: [
            {
                id: 56836,
                name: 'Walking Home',
                src: 'https://ipfs.io/ipfs/QmatrNGiVEo5RjNkV27CS2WgwhQkN7i4xN7azLrUewycXB',
                mimeType: 'audio/mpeg',
                creator: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX',
            },
            {
                id: 52492,
                name: 'Stronger (Yeti Tears Remix)',
                src: 'https://ipfs.io/ipfs/QmWHAQEhYuWka4hXx5MQx773tW8ZY76rdJ2io6VfrFECnV',
                mimeType: 'audio/mpeg',
                creator: 'ttz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX',
            },
            {
                id: 40382,
                name: 'The Portal',
                src: 'https://ipfs.io/ipfs/QmWRJpiSnDcu76NvUq9CkY1U2cVaP8Z75G3nArnqbQ1eGa',
                mimeType: 'audio/mpeg',
                creator: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX',
            },
            {
                id: 35832,
                name: 'Aerophobia',
                src: 'https://ipfs.io/ipfs/QmekqLeahzokRF8S6PoRUj6mvXn3xJWErr6oMePkq8pQUX',
                mimeType: 'audio/mpeg',
                creator: 'tz1ceWH6Sd1iM15LPHUjYBFrmjeufirPzjhX',
            },
        ],
    },
    {
        name: 'Cryptobeat',
        curator: 'HEN Radio',
        description: 'Cryptobeat glitch',
        img: playlistCoverSeven,
        tracks: [
            {
                id: 58421,
                name: 'CIRCLE COMPLETE (production GLASSY)',
                src: 'https://ipfs.io/ipfs/QmUVqJPzx9v6WDeWVxxVSe1PrMyibyWtFnioAR7sY42tyG',
                mimeType: 'audio/mpeg',
                creator: 'ttz1ZtxSzCJkDNztv2QRP8xgVLafxv9D5aYea',
            },
            {
                id: 39331,
                name: 'CANNABIS SAINTS BEAT TAPE [Song 1 Glory and Time]',
                src: 'https://ipfs.io/ipfs/QmVRU7oG6RnJ6dQ1QAUm1Doji2Nfu2cuuCVmBjYNtrHahq',
                mimeType: 'audio/mpeg',
                creator: 'tz1ZtxSzCJkDNztv2QRP8xgVLafxv9D5aYea',
            },
        ],
    },
    {
        name: 'Trance',
        curator: 'HEN Radio',
        description: 'Psychedelic Trance',
        img: playlistCoverFive,
        tracks: [
            {
                id: 34506,
                name: 'Poliwog - UNR Work In Progress',
                src: 'https://ipfs.io/ipfs/Qmc7rFFKmUzasjej9y3tkjc1kwrWQPjPWdK2gNdFFymdbu',
                mimeType: 'audio/mpeg',
                creator: 'tz1MUcbDL1UbE4DTibDuDs8dLnih4u6Ka8uT',
            },
            {
                id: 77720,
                name: 'Unreleased Psychedelic Trance Track 2 by Poliwog',
                src: 'https://ipfs.io/ipfs/QmQpPXELuT88xHpKo7FF4F68pv2vDe7txkXMDYo6fH3nQ7',
                mimeType: 'audio/mpeg',
                creator: 'tz1MUcbDL1UbE4DTibDuDs8dLnih4u6Ka8uT',
            },
        ],
    },
];
